### PR TITLE
ply files with quad faces

### PR DESCRIPTION
**Pull request by Rabbid76**
The solution might be some kind of hack, however it solves the issue for me.
[PLY files with QUAD faces are not read correctly #32](https://github.com/cnr-isti-vclab/corto/issues/32)
It's up to you if you want to merge it, I'll use it anyway until you finally implement it.

### CODE REVIEW

**Comment by ponchio** [comment]
I used a slightly different approach: I tessellate the polygon (quad pentagon exagon etc) and just resize the index vector (instead of reserving twice the space required). whenever the listSize is > 3
This should also work with per wedge texture coordinates (even though didn't really tested it), and the number of triangle is recovered from the vector size anyway.

I added the u,v s,t coords following your code, and also vertex_index (seen in some .plys)

Could you test my code on your models?

**Comment by Rabbid76** [comment]
Hello, thank you for your quick reply.
I tested the latest master, unfortunately it doesn't work for me. When I load the ASCII-ply from #32, I get a number of 70 faces (`crt::MeshLoader::nface`). However, the mesh only has 10 quad faces, so I'm expecting 20 triangular faces.

Here is the binary and ASCII version of the ply file:

[plyfiles.zip](https://github.com/cnr-isti-vclab/corto/files/7921147/plyfiles.zip)

**Comment by ponchio** [comment]
The count for additional indexes was a bit off. Didn't notice because the extra indexes where all zeros and ignored by the encoder.
Should be fixed now.

**Comment by Rabbid76** [comment]
Thanks it works as intended now

**Pull request closed without merging**
